headersOrigin = "config"
plugins = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/thadeu/code/opensource-me/blog/dist"
publishOrigin = "config"
command = "npm run build"
commandOrigin = "config"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]
pretty_urls = false

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/assets/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"